default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  host: 127.0.0.1
  database: show_time_dev
  username: root
  password: ""

test:
  <<: *default
  host: 127.0.0.1
  database: show_time_test
  username: root
  password: ""

production:
  <<: *default
  host: 127.0.0.1
  database: show_time_pro
  username: root
  password: ""
